server:
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likelion_board
    username: test
    password: test

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
